### ISSUE TITLE
Release arm64 binaries

### ISSUE THREAD

**Issue by mesaugat** [pratishshr/envault#25]
Right now the curl script won't work in arm machines. Starting with `go1.16` --> `darwin/arm64` platform is supported. With the new `goreleaser` arm64 binaries will be built by default.

I had to fork the repo and run `goreleaser` myself to get the arm binary that works on my M1 mac. No configuration changes were required for `goreleaser`.

**Comment by pratishshr** [comment]
@mesaugat 

Added. Should work now.
https://github.com/pratishshr/envault/releases/tag/v1.1.11

**Comment by mesaugat** [comment]
@pratishshr 💯  Yep, I used the curl command to download the binary after seeing your commit before you made this comment. 😅 

Works now.
